export default {
  enterPhoneNumber: 'Введите Ваш номер телефона для входа',
  phoneInput: 'Номер телефона',
  acceptAgreement: 'Нажимая кнопку "Войти" Вы принимаете условия Пользовательского соглашения',
  getSms: 'Получить смс с кодом',
  signIn: 'Вход',
  enterCode: 'Код подтверждения',
  enterCodeText: 'Мы отправили смс с кодом подтверждения на номер ',
  uncorrectNumber: 'Неправильный номер',
  register: 'Регистрация',
  required: 'обязательные поля для заполнения',
  ready: 'Готово',
  name: 'Имя',
  surname: 'Фамилия',
  sex: 'Пол',
  chooseCity: 'Выберите город',
  fromWhere: 'Откуда Вы узнали о нашем сервисе ?',
  male: 'Мужской',
  female: 'Женский',
  registerMaster: 'Регистрация Мастера',
  birthdayDate: 'Дата рождения',
  masterType: 'Тип Мастера',
  chooseSpec: 'Выберите одну или несколько специализаций.',
  'spec/s': 'специализации',
  uncorrectCodeTryAgain: 'Неправильный код, попробуйте еще раз!',
  yourPhoneNumber: 'Ваш номер телефона',
  login: 'Войти',
};
