export default {
  order: 'Заказ',
  create: 'Создать заказ',
  myOrders: 'Мои заказы',
  listOrder: 'Лента заказов',
  notification: 'Уведомления',
  howItWorks: 'Как это работает?',
  news: 'Новости',
  readyToTake: 'Готов взяться за работу',
  offerPrice: 'Предлагаю Вам цену',
  solveWithClient: 'Позвоните, пжста, обсудим детали по тел.',
  allMasters: 'Все Мастера',
  current: 'Текущие',
  finished: 'Завершенные',
  orders1: 'Заказы',
  orders: 'Заказов',
  responds: 'Отклики',
  myOrder: 'Мой заказ',
  masters: 'Мастера',
  markets: 'Товары',
  cancelOrder: 'Отменить заказ',
  editOrder: 'Редактировать заказ',
  finishOrder: 'Завершить заказ',
  noOrders: 'У Вас нет заказов',
  noResponds: 'У Вас нет откликов',
  noFinishedOrders: 'У Вас нет завершенных заказов',
  agreedWithMaster: 'Договорились с Мастером ?',
  finishedOrders: 'Завершенные заказы',
  wroteToYou: 'Вам писали',
  calledToYou: 'Вам звонили',
  orderBecomeNotActual: 'Заказ стал не актуален',
  notFoundMaster: 'Не нашел на Сервисе подходящего Мастера',
  foundWithAnotherService: 'Нашел другим способом(не ч/з Сервис)',
  causeOfFinish: 'Можем ли мы узнать причину отмены ?',
  another: 'Другое',
  repeat: 'Повторить',
  repeatOrder: 'Повторить заказ',
  createOrderAgain: 'Создать заказ повторно',
  allMarkets: 'Товары',
};
