export default {
  masters: 'Мастера',
  cancel: 'Отмена',
  answersWillBeReset: 'Ваши ответы будут сброшены',
  resetAndQuit: 'Сбросить и выйти',
  close: 'Закрыть',
  closeWindow: 'Закрыть окно',
  showMore: 'См.еще',
  selectFromGallery: 'Выбрать из галереи',
  makePhoto: 'Сделать снимок',
  addPhoto: 'Добавить фотографию',
  closeMap: 'Закрыть карту',
  yes: 'Да',
  no: 'Нет',
  created: 'Создан',
  accept: 'Принять',
  call: 'Позвонить',
  onPortal: 'На портале',
  onPortalToday: 'На портале сегодня зарегистрирован',
  day1: 'день',
  day2: 'дня',
  day3: 'дней',
  month1: 'месяц',
  month2: 'месяца',
  month3: 'месяцев',
  year1: 'год',
  year2: 'года',
  year3: 'лет',
  wasOnline: 'Был(а) в сети',
  saveChanges: 'Сохранить изменения',
  save: 'Сохранить',
  edittingWillBeCanceled: 'Редактирование будет отменено',
  creatingWillStop: 'Создание будет отменено',
  categories: 'Категории',
  specs: 'Специализации',
  aboutApp: 'О приложении',
  confidential: 'Конфиденциальность',
  agreement: 'Соглашение пользователя',
  settings: 'Настройки',
  noInfo: 'Нет информации',
  noPhoto: 'Фото не предоставлены',
  noVideo: 'Видео не предоставлено',
  noServices: 'Услуги не предоставлены',
  noReviews: 'Нет отзывов',
  noNews: 'Новостная лента пустая',
  createToSee: 'Создайте заказ чтобы увидеть контакты этого Мастера, а также других.',
  youCanCall: 'Вы можете звонить сразу напрямую, не дожидаясь откликов.',
  toCall: 'Чтобы связаться с выбранным Мастером создайте заказ',
  ifAgreedWeWillSend: 'Договорились? Если "Да", мы отправим уведомление Мастеру',
  noMastersAtThisMoment: 'В данный момент нет Мастеров по Вашему заказу',
  noMastersAtThisMoment2: 'В данный момент нет Мастеров',
  next: 'Далее',
  anotherNews: 'Другие новости',
  ready: 'Готово',
  pressToChoose: 'Нажмите на фото чтобы выбрать',
  logOut: 'Выйти из аккаунта',
  contactNumber: 'Контактный номер',
  confirmDoc: 'Подтверждающий документ',
  confirmDocText: 'Документы нужны для безопасности совершения сделок',
  iin: 'ИИН',
  chooseForID: 'Выбрать фото удостоверения личности',
  choose: 'Выберите',
  back: 'Назад',
  chooseForID2: 'Выбрать фото обратной стороны удостоверения личности',
  pressToEdit: 'Нажмите редактировать чтобы добавить (правый верхний угол (значок карандаша))',
  delete: 'Удалить',
  sureDeleteService: 'Вы точно хотите удалить эту Услугу ?',
  sureDeleteImage: 'Вы точно хотите удалить изображение ?',
  filtres: 'Фильтры',
  allOrders: 'Все заказы',
  myResponds: 'Мои отклики ',
  noOrdersBySpecs: 'По Вашим специализациям нет заказов',
  youWrote: 'Вы писали',
  youCall: 'Вы звонили',
  promos: 'Акции',
  noPromos: 'Нет Акции и Скидок',
  noNots: 'Нет уведомлений',
  markAsRead: 'Отметить все как прочитанные',
  time: 'Время',
  acceptedOrder: 'Вы успешно приняли заказ',
  agreedWithClient: ' Договорились с Заказчиком по заказу',
  noMarkets: 'В данный момент нет товаров',
  aboutOrg: 'О компании',
  workSchedule: 'График работы',
  break: 'перерыв',
  sunday: 'воскресенье',
  saturday: 'суббота',
  mnfr: 'пн-пт',
  productsAndPrices: 'Товары и цены',
  write: 'Откликнуться',
  faq: 'Популярные вопросы',
  wasHelpful: 'Вам была полезна данная информация?',
  noQuestions: 'Нет вопросов',
  writeToMaster24: 'Обратиться в Master24.kz',
  support: 'Служба поддержки',
  writeQuestion1: 'Напишите Ваш вопрос',
  writeQuestion2: 'Напишите Вашу жалобу',
  writeQuestion3: 'Напишите Ваше предложение',
  infoToQuestions: 'Ознакомьтесь с Популярными вопросами, либо задайте свой вопрос ниже.',
  question1: 'Вопрос',
  question2: 'Жалоба',
  question3: 'Предложение',
  send: 'Отправить',
  thanksForSend: 'Спасибо за обращение',
  thanksForSend2: 'Спасибо! В самое ближайшее время наш менеджер свяжется с Вами!',
  thanksForSend3: 'Также Вы можете самостоятельно нам позвонить +7 707 777 03 16',
  thanksForSend4: 'Мы на связи ежедневно с 09:00 до 18:00',
  happenedError: 'Произошла ошибка',
  blockedAcc: 'Ваш аккаунт заблокирован!',
  change: 'Изменить',
  hide: 'скрыть',
  readAll: 'читать полностью',
  customerGrage: 'Оценка Заказчика',
  noGrade: 'Заказчик не оставил оценку Вашей работы',
  finishWork: 'Завершить заказ',
  waitForCustomer: 'Ждём подтверждение Заказчика',
  finishOrderText:
    ' После того как Вы нажмёте «Завершить», мы отправим уведомление Заказчику для подтверждения',
  finish: 'Завершить',
  aboutMaster: 'Какие впечатления от Мастера ?',
  gradeMaster: 'Оцените Мастера',
  finished: 'завершен',
  cannotCall: 'Заказчик пожелал убрать возможность звонка от Мастеров.',
  writeToOrder: 'Откликнуться на заказ №',
  alreadyResponded: 'Вы уже откликались на этот заказ',
  notAllowed: 'Запрещено',
  cannotRespondOwn: 'Вы не можете откликаться на свой заказ',
  addService: 'Добавить услугу',
  addServiceAndPrice: 'Добавить Услугу и Цену',
  serviceName: 'Название услуги',
  price: 'Цена',
  metrics: 'Ед. измерения(тг, тг/кв. м, тг/мин и т.д.)',
  create: 'Создать',
  successMasterChoosed: 'Мастер успешно выбран',
  updateVideo: 'Обновить видео',
  addVideo: 'Добавить видео',
  linkToVideo:
    'Ссылка на видео в Youtube(Чтобы взять ссылку с Youtube, нажмите кнопку поделиться и копировать ссылку)',
  uncorrectVideo: ' Неправильная ссылка. Ссылка должна начинаться на https://youtu.be/',
  exmpleVideo: 'Пример: https://youtu.be/5-4TgpDYPwg',
  updateSpec: 'Обновить специализацию',
  waitAnswearFromCustomer: 'Ждите ответа от Заказчика',
  alreadyInProgress: 'Заказ уже в работе',
  alreadyFinished: 'Заказ уже завершен',
  restart: 'Перезапуск',
  restartText: 'Для применения изменений требуется перезапустить приложение',
  today: 'сегодня в',
  thanks: 'Спасибо',
};
