export default {
  enterPhoneNumber: 'Кіру үшін телефон нөміріңізді енгізіңіз',
  phoneInput: 'Телефон нөмірі',
  acceptAgreement: '«Кіру» түймесін басу арқылы Сіз Пайдаланушы келісімінің шарттарын қабылдайсыз',
  getSms: 'Коды бар смс-ты қабылдау',
  signIn: 'Кіру',
  enterCode: 'Расстама коды',
  enterCodeText: 'Расстау коды бар смсты мына нөмерге жібердік ',
  uncorrectNumber: 'Қате нөмер',
  register: 'Тіркелу',
  required: 'Толтыру қажет',
  ready: 'Дайын',
  name: 'Аты',
  surname: 'Тегі',
  sex: 'Жынысы',
  chooseCity: 'Қаланы таңдаңыз',
  fromWhere: 'Біз жайлы кайдан білдіңіз',
  male: 'Ер',
  female: 'Әйел',
  registerMaster: 'Мастерді тіркеу',
  birthdayDate: 'Туған күніңіз',
  masterType: 'Мастердің күйі',
  chooseSpec: 'Бір немесе бірншеше мамандық таңдаңыз',
  'spec/s': 'мамандык/тар',
  uncorrectCodeTryAgain: 'Код қате терілген, қайта теріңіз!',
  yourPhoneNumber: 'Сіздің телефон нөмеріңіз',
  login: 'Кіру',
};
