export default {
  order: 'Тапсырыс',
  create: 'Тапсырыс ашу',
  readyToTake: 'Жұмысқа кірісуге дайынмын',
  offerPrice: 'Сізге бағаны ұсынамын',
  solveWithClient: 'Телефон арқылы егжей-тегжейлі талқылайық',
  allMasters: 'Барлық мастерлар',
  current: 'Ағымдағы',
  finished: 'Аяқталды',
  orders: 'Тапсырыстар',
  orders1: 'Тапсырыстар',
  responds: 'Ұсыныстар',
  myOrder: 'Тапсырысым',
  masters: 'Мастерлер',
  markets: 'Тауарлар',
  cancelOrder: 'Тапсырысты жою',
  editOrder: 'Тапсырысты өңдеу',
  finishOrder: 'Тапсырысты аяқтау',
  noOrders: 'Сізде тапсырыстар жоқ',
  noResponds: 'Сізде ұсыныстар жоқ',
  noFinishedOrders: 'Сізде аяқталған тапсырыстар жоқ',
  agreedWithMaster: 'Мастермен келісе алдыңызба ?',
  finishedOrders: 'Аяқталған тапсырыстар',
  wroteToYou: 'Сізге жазды',
  calledToYou: 'Сізге хабарласты',
  orderBecomeNotActual: 'Тапсырыс қажет болмай қалды',
  notFoundMaster: 'Сервистен қажет Мастерді таппадым',
  foundWithAnotherService: 'Басқа жолмен таптым (Сервис арқылы емес)',
  causeOfFinish: 'Бас тарту себебін біле аламыз ба?',
  another: 'Басқа',
  repeat: 'Қайталау',
  repeatOrder: 'Тапсырысты қайталау',
  createOrderAgain: 'Тапсырысты қайта ашу',
  allMarkets: 'Тауарлар',
};
