export default {
  masters: 'Мастерлер',
  cancel: 'Болдырмау',
  answersWillBeReset: 'Терілген мәліметтер өшіп кетеді',
  resetAndQuit: 'Қалпына келтіру және шығу',
  close: 'Жабу',
  closeWindow: 'Терезені жабу',
  showMore: 'Тағы көру',
  selectFromGallery: 'Галереядан таңдау',
  makePhoto: 'Фотоға түсіру',
  addPhoto: 'Фото таңдау',
  closeMap: 'Картаны жабу',
  yes: 'Иа',
  no: 'Жоқ',
  created: 'Берілді',
  accept: 'Қабылдау',
  call: 'Қоңырау шалу',
  onPortal: 'Порталда',
  onPortalToday: 'Порталға бүгін тіркелген',
  day1: 'күн',
  day2: 'күн',
  day3: 'күн',
  month1: 'ай',
  month2: 'ай',
  month3: 'ай',
  year1: 'жыл',
  year2: 'жыл',
  year3: 'жыл',
  wasOnline: 'Желіде болды:',
  saveChanges: 'Өзгерістерді сақтау',
  edittingWillBeCanceled: 'Өңдеу тоқтатылады',
  creatingWillStop: 'Қайта ашу тоқтатылады',
  categories: 'Категориялар',
  specs: 'Специализациялар',
  aboutApp: 'Қосымша туралы',
  confidential: 'Құпия',
  agreement: 'Тұтынушы келісім шарты',
  settings: 'Баптаулар',
  noInfo: 'Ақпарат берілмеген',
  noPhoto: 'Фото берілмеген',
  noVideo: 'Видео берілмеген',
  noReviews: 'Пікірлер жоқ',
  noNews: 'Жаңалықтар таспасы бос',
  createToSee: 'Осы жәнеде басқада Мастерлердің контактілерін көру үшін тапсырыс жасаңыз.',
  youCanCall: 'Сіз кері байланыс күтпей-ақ тікелей қоңырау шала аласыз.',
  toCall: 'Таңдалған Мастермен байланысу үшін тапсырыс жасаңыз',
  ifAgreedWeWillSend: 'Сіздер келістіңіздер ме? "Ия" болса, біз Мастерге хабарлама жібереміз',
  noMastersAtThisMoment: 'Қазіргі уақытта тапсырысыңыз бойынша Мастерлер жоқ',
  noMastersAtThisMoment2: 'Қазіргі уақытта Мастерлер жоқ',
  next: 'Келесі',
  anotherNews: 'Басқа жаңалықтар',
  ready: 'Дайын',
  pressToChoose: 'Таңдау үшін фотоға басыңыз',
  logOut: 'Аккаунттан шығу',
  save: 'Сақтау',
  contactNumber: 'Байланыс нөмірі',
  confirmDoc: 'Растаушы құжаттар',
  confirmDocText: 'Құжаттар тапсырыстың қауіпсіздігі үшін қажет ',
  iin: 'ЖСН',
  chooseForID: 'Жеке куәліктің суретін таңдау',
  choose: 'Таңдаңыз',
  back: 'Артқа',
  chooseForID2: 'Жеке куәліктің артқы суретін таңдау',
  pressToEdit: 'Қосу үшін өңдеуді басыңыз (жоғарғы оң жақ бұрыш (қарындаш белгішесі))',
  delete: 'Жою',
  sureDeleteService: 'Осы қызметті жою керек пе?',
  sureDeleteImage: 'Суретті шынымен жойғыңыз келе ме?',
  filtres: 'Фильтрлер',
  allOrders: 'Тапсырыстар',
  myResponds: 'Ұсыныстарым',
  noOrdersBySpecs: 'Сіздің мамандығыңыз бойынша тапсырыс жоқ.',
  youWrote: 'Сіз жаздыңыз',
  youCall: 'Сіз хабарластыңыз',
  promos: 'Акциялар',
  noPromos: 'Акциялар мен жеңілдіктер жоқ',
  noNots: 'Хабарламалар жоқ',
  markAsRead: 'Барлығын оқылған деп белгілеу',
  time: 'Уақыт',
  acceptedOrder: 'Сіз тапсырысты сәтті қабылдадыңыз',
  agreedWithClient: 'Тапсырыс берушімен мына тапсырыс бойынша келісе алдыңызба: ',
  noMarkets: 'Қазіргі уақытта тауарлар жоқ.',
  aboutOrg: 'Компания жайлы',
  workSchedule: 'Жұмыс кестесі',
  break: 'үзіліс',
  sunday: 'жексенбі',
  saturday: 'сенбі',
  mnfr: 'дб-жм',
  productsAndPrices: 'Тауарлар мен бағалар',
  write: 'Ұсыныс беру',
  faq: 'Танымал сұрақтар',
  wasHelpful: 'Бұл ақпарат Сізге пайдалы болды ма?',
  noQuestions: 'Сұрақтар жоқ',
  writeToMaster24: 'Master24.kz пен байланысу',
  support: 'Қолдау қызметі',
  writeQuestion1: 'Сұрағыңызды жазыңыз',
  writeQuestion2: 'Шағымығызды жазыңыз',
  writeQuestion3: 'Ұсынысыңызды жазыңыз',
  infoToQuestions: 'Төменде біздің басты сұрақтарымызды қараңыз немесе өз сұрақтарыңызды қойыңыз.',
  question1: 'Сұрақ',
  question2: 'Шағым',
  question3: 'Ұсыныс',
  send: 'Жіберу',
  thanksForSend: 'Байланыс үшін рахмет',
  thanksForSend2: 'Рахмет! Жақын арада біздің менеджер Сізбен хабарласады!',
  thanksForSend3: 'Сондай-ақ, Сіз бізге +7 707 777 03 16 нөмірі бойынша қоңырау шала аласыз',
  thanksForSend4: 'Біз күн сайын 09:00-ден 18:00-ге дейін байланыс жасаймыз',
  happenedError: 'Қате орын алды',
  blockedAcc: 'Есептік жазбаңыз бұғатталды!',
  change: 'Өзгерту',
  hide: 'жасыру',
  readAll: 'толық оқу',
  customerGrage: 'Клиенттің бағасы',
  noGrade: 'Тапсырыс беруші Сіздің жұмысыңызға баға қалдырған жоқ',
  finishWork: 'Тапсырысты аяқтау',
  waitForCustomer: 'Тұтынушы растауын күтудеміз',
  finishOrderText:
    '«Аяқтау» түймесін басқаннан кейін, біз растау үшін Тапсырысшыға хабарлама жібереміз',
  finish: 'Аяқтау',
  aboutMaster: 'Мастердің жұмысына қандай пікір бересіз ?',
  gradeMaster: 'Мастерді бағалаңыз',
  finished: 'аяқталды',
  cannotCall: 'Тапсырыс беруші Мастерлерден қоңырау қабылдау мүмкіндігін алып тастады.',
  writeToOrder: 'Мына нөмірдегі тапсырысқа ұсыныс беру: ',
  alreadyResponded: 'Сіз бұл тапсырысқа ұсыныс бердіңіз',
  notAllowed: 'Тыйым салынған',
  cannotRespondOwn: 'Сіз өз тапсырысыңызға ұсыныс бере алмайсыз',
  addService: 'Қызметті қосу',
  addServiceAndPrice: 'Қызмет және бағаны қосу',
  serviceName: 'Қызмет атауы',
  price: 'Баға',
  metrics: 'Бірліктер өлшемі(тг, тг/кв. м, тг/мин и т.д.)',
  create: 'Жасау',
  successMasterChoosed: 'Мастер сәтті таңдалды',
  updateVideo: 'Видеоны жаңарту',
  addVideo: 'Видеоны қосу',
  linkToVideo:
    'Youtube сайтындағы бейнеге сілтеме (Youtube-тен сілтеме алу үшін, бөлісу түймесін басып, сілтемені көшіріңіз)',
  uncorrectVideo: ' Жарамсыз сілтеме. Сілтеме https://youtu.be/ сайтында басталуы керек',
  exmpleVideo: 'Мысал: https://youtu.be/5-4TgpDYPwg',
  noServices: 'Қызметтер көрсетілмеген',
  updateSpec: 'Специализацияларды жаңарту',
  waitAnswearFromCustomer: 'Клиенттен жауап күтіңіз',
  alreadyInProgress: 'Тапсырыс қазір жасалуда',
  alreadyFinished: 'Тапсырыс аяқталды',
  restart: 'Қайта іске қосу',
  restartText: 'Өзгерістерді қолдану үшін қосымшаны қайта іске қосу керек',
  today: 'бүгін',
  thanks: 'Рахмет',
};
